name: imc_terminal_calc
description: A command-line IMC calculator.
version: 1.0.0
repository: https://github.com/GuilhermeAlecrim7K/imc_terminal_calc

environment:
  sdk: ^3.1.0

dependencies:

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
